# Generated by Django 5.0.2 on 2024-02-19 18:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserAccount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('tg_id', models.TextField(unique=True)),
                ('phone_number', models.CharField(max_length=12, unique=True)),
                ('tg_nickname', models.CharField(max_length=32)),
                ('registration_date', models.DateTimeField(auto_now_add=True)),
                ('last_login_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
