# Generated by Django 5.0.2 on 2024-03-26 12:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='useraccount',
            name='last_login_date',
        ),
    ]
